### ISSUE TITLE
Dokumentacija

### ISSUE THREAD

**Issue by VojislavM** [Elektropioneer/Odometrija_firmware#1]
@MarkoKozomora molim te da samo napises koju recenicu u [README.md](https://github.com/Elektropioneer/Odometrija_final_code/blob/master/README.md) fajlu, cisto zbog lakseg snalazenja kasnije i da bi ostali znali o cemu se radi detaljnije.

Pozdrav

**Comment by MarkoKozomora** [comment]
Ok, reseno :D naravno svaka ovakva opomena je bitna jer sam ja ocigledno prevideo to da ostavim neki komentar.

**Comment by VojislavM** [comment]
@MarkoKozomora ja sam jos malo prepravio readme. Tu treba da ti pisu neke osnovne stvari o repozitorijumu, sta se tu nalazi. 

Ono sto je ispravljeno to napises u poruci commit-a ili ako je nesto duze i vaznije (nova ili dodatna funkcionalnost), onda dodaj u readme kao sto sam ja uradio za 1.0

Mozes dodati jos par stvari poput, koji je kompajler, koji IDE koristis, itd. Sve to treba da ti pomogne kad se ponovo vratis na taj kod. :)

**Comment by MarkoKozomora** [comment]
Ok, vidim kako si uradio tako da znam za sledeci put.....jbg nemam bas iskustva :/

**Comment by VojislavM** [comment]
Nije problem, ja ti samo pomazem, ako negde zapne slobodno pitaj :wink:

**Comment by MarkoKozomora** [comment]
Ok hvala :)
